name: Ejecucion de comandos en paralelo (selfthosted)

on:
  push:
    branches:
      - main

jobs:    
  comandos-paralelo:
    runs-on: self-hosted
    strategy:    
      matrix:
        folder: [a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z]
    steps:

      - name: Step 1 - Listado de directorios
        run: ls -la
        
      - name: Step 2 - Creacion de directorio
        run: mkdir ${{ matrix.folder }}

      - name: Step 3 - Creacion de archivos en directorio
        run: |
          cd ${{ matrix.folder }}
          echo 'Primer mensajes'    > archivo01.txt
          echo 'Segundo mensajes'    > archivo02.txt
          echo 'Tercer mensajes'    > archivo03.txt                    
          cd ..
      - name: Step 4 - Listado de directorios y archivos
        run: ls -la  ${{ matrix.folder }}
        
      - name: Step 5 - visualizacion de contendidos
        run: |      
          cd ${{ matrix.folder }}
          cat archivo01.txt
          cat archivo02.txt
          cat archivo03.txt
