name: Matrices de opciones

on:
  push:
    branches:
      - main14
jobs:
  setup:
    runs-on: ubuntu-latest

    strategy:    
      matrix:
        cc: [gcc, clang]
        curl: [openssl, gnutls, nss] 
        kerberos: [libkrb5, heimdal]        

    steps:
    - name: Show hostname
      run: 
        cat /proc/sys/kernel/hostname
    - name: Install dependencies
      run: |        
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.cc }} \
                                libcurl4-${{ matrix.curl }}-dev \
                                ${{ matrix.kerberos }}-dev 
