name: Matrices de opciones

on:
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest

    strategy:    
      matrix:
        cc: [gcc, clang]        
        curl: [openssl, gnutls, nss]
        kerberos: [libkr5, heimdal]

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.cc }} \
                                libcur14-${{ matrix.cc }}-dev \
                                ${{ matrix.kerberos }}-dev
        
